-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 17:37:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `projeto_integrador` ;

-- -----------------------------------------------------
-- Table `projeto_integrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoria_horta` TINYINT NULL,
  `categoria_mercearia` TINYINT NULL,
  `categoria_mista` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `produto_nome` VARCHAR(255) NOT NULL,
  `produto_foto` VARCHAR(255) NOT NULL,
  `produto_preco` DECIMAL(9,2) NOT NULL,
  `produto_tamanho` VARCHAR(10) NOT NULL,
  `produto_produtora` VARCHAR(255) NOT NULL,
  `produto_descricao` TEXT NOT NULL,
  `usuario_id` BIGINT NULL,
  `categorias_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projeto_integrador`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `projeto_integrador`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
